### ISSUE TITLE
Hardware model/DLL Irdroid

### ISSUE THREAD

**Issue by Irdroid** [leg0/WinLIRC#3]
Hello, 

During the last year we have extensively tested the new hardware support for Irdroid USB modules (DLL already in the repository) with winlirc, is it possible to compile in next version of winlirc with hardware support for Irdroid?

Thanks

**Comment by leg0** [comment]
Are you asking me to make a new release or are you asking whether building the irdroid dll works?

**Comment by Irdroid** [comment]
I am asking for a new release. The unit was already tested during the last 10 months with the DLL

**Comment by leg0** [comment]
Sure, I can make a new release

**Comment by Irdroid** [comment]
Thank you!

**Comment by leg0** [comment]
Created release 1.0.0
